/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import common.Utils;
import dao.UserDao;
import dao.VoucherDao;
import java.awt.Component;
import java.time.LocalDate;
import javax.swing.DefaultListCellRenderer;
import javax.swing.JList;
import javax.swing.table.DefaultTableModel;
import model.Rank;
import model.Staff;
import model.Voucher;

/**
 *
 * @author Admin
 */
public class ManageVoucher extends javax.swing.JFrame {

    /**
     * Creates new form ManageVoucher
     */
    public ManageVoucher() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtMinCost = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblVouchers = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        cbxRank = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtMaxDiscountAmount = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtDiscountPercentage = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        dpExpDate = new com.toedter.calendar.JDateChooser();
        chbxAmountOnly = new javax.swing.JCheckBox();
        chbxPercentageOnly = new javax.swing.JCheckBox();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1194, 719));
        setMinimumSize(new java.awt.Dimension(1194, 719));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1194, 719));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtMinCost.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtMinCost.setText("0");
        txtMinCost.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtMinCostKeyReleased(evt);
            }
        });
        getContentPane().add(txtMinCost, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 230, 110, -1));

        btnSave.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/save.png"))); // NOI18N
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        getContentPane().add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 490, -1, -1));

        btnClear.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/clear.png"))); // NOI18N
        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        getContentPane().add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 490, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("%");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 320, -1, 20));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/category.png"))); // NOI18N
        jLabel1.setText("Manage Voucher");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 12, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Voucher List");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 50, 100, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/close.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 10, -1, -1));

        tblVouchers.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tblVouchers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Voucher", "Min Rank", "Exp. Date"
            }
        ));
        tblVouchers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblVouchersMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblVouchers);
        if (tblVouchers.getColumnModel().getColumnCount() > 0) {
            tblVouchers.getColumnModel().getColumn(0).setMinWidth(0);
            tblVouchers.getColumnModel().getColumn(0).setPreferredWidth(0);
            tblVouchers.getColumnModel().getColumn(0).setMaxWidth(0);
            tblVouchers.getColumnModel().getColumn(2).setPreferredWidth(100);
            tblVouchers.getColumnModel().getColumn(2).setMaxWidth(100);
            tblVouchers.getColumnModel().getColumn(3).setPreferredWidth(100);
            tblVouchers.getColumnModel().getColumn(3).setMaxWidth(100);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 90, 690, 550));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Add New Voucher");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, -1, -1));

        cbxRank.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(cbxRank, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 180, 170, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Minimum Rank");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, -1, 20));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Expiration Date");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 420, -1, 20));

        txtMaxDiscountAmount.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtMaxDiscountAmount.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtMaxDiscountAmountKeyReleased(evt);
            }
        });
        getContentPane().add(txtMaxDiscountAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 370, 110, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Minimum Cost");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, -1, 20));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("$");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 370, -1, 20));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Discount Percentage:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 320, -1, 20));

        txtDiscountPercentage.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtDiscountPercentage.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDiscountPercentageKeyReleased(evt);
            }
        });
        getContentPane().add(txtDiscountPercentage, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 320, 110, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("$");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 230, -1, 20));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Max discount amount");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 370, -1, 20));

        dpExpDate.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                dpExpDatePropertyChange(evt);
            }
        });
        getContentPane().add(dpExpDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 420, 170, -1));

        chbxAmountOnly.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        chbxAmountOnly.setForeground(new java.awt.Color(255, 255, 255));
        chbxAmountOnly.setText("Use amount only");
        chbxAmountOnly.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chbxAmountOnlyActionPerformed(evt);
            }
        });
        getContentPane().add(chbxAmountOnly, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 270, -1, 30));

        chbxPercentageOnly.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        chbxPercentageOnly.setForeground(new java.awt.Color(255, 255, 255));
        chbxPercentageOnly.setText("Use percentage only");
        chbxPercentageOnly.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chbxPercentageOnlyActionPerformed(evt);
            }
        });
        getContentPane().add(chbxPercentageOnly, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, -1, 30));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/full-page-background.PNG"))); // NOI18N
        jLabel13.setText("jLabel13");
        jLabel13.setMaximumSize(new java.awt.Dimension(1021, 619));
        jLabel13.setMinimumSize(new java.awt.Dimension(1021, 619));
        jLabel13.setPreferredSize(new java.awt.Dimension(1021, 619));
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 1210, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtMinCostKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMinCostKeyReleased
        validateFields();
    }//GEN-LAST:event_txtMinCostKeyReleased

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        Voucher voucher = new Voucher();
        voucher.setMinRank((Rank) cbxRank.getSelectedItem());
        voucher.setMinCost(Double.parseDouble(txtMinCost.getText()));
        voucher.setDiscountPercentage(txtDiscountPercentage.getText().isEmpty() ? -1 : Double.parseDouble(txtDiscountPercentage.getText()));
        voucher.setMaxDiscountAmount(txtMaxDiscountAmount.getText().isEmpty() ? -1 : Double.parseDouble(txtMaxDiscountAmount.getText()));
        voucher.setExpDate(Utils.toLocalDate(dpExpDate.getDate()));

        VoucherDao.getInstance().save(voucher);
        btnClearActionPerformed(null);
        loadVouchers();
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        cbxRank.setSelectedIndex(0);
        txtMinCost.setText("");
        chbxPercentageOnly.setSelected(false);
        chbxPercentageOnlyActionPerformed(null);
        chbxAmountOnly.setSelected(false);
        chbxAmountOnlyActionPerformed(null);
        txtDiscountPercentage.setText("");
        txtMaxDiscountAmount.setText("");
        dpExpDate.setDate(null);

        validateFields();
    }//GEN-LAST:event_btnClearActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tblVouchersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblVouchersMouseClicked

    }//GEN-LAST:event_tblVouchersMouseClicked

    private void txtMaxDiscountAmountKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMaxDiscountAmountKeyReleased
        validateFields();
    }//GEN-LAST:event_txtMaxDiscountAmountKeyReleased

    private void txtDiscountPercentageKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDiscountPercentageKeyReleased
        validateFields();
    }//GEN-LAST:event_txtDiscountPercentageKeyReleased

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        cbxRank.setRenderer(new DefaultListCellRenderer() {
            @Override
            public Component getListCellRendererComponent(JList<?> list, Object value, int index, boolean isSelected, boolean cellHasFocus) {
                super.getListCellRendererComponent(list, value, index, isSelected, cellHasFocus);
                if (value instanceof Rank rank) {
                    setText(rank.getName());
                }
                return this;
            }
        });
        UserDao.getInstance().getAllRanks().forEach(cbxRank::addItem);

        loadVouchers();
    }//GEN-LAST:event_formComponentShown

    private void chbxPercentageOnlyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chbxPercentageOnlyActionPerformed
        if (chbxPercentageOnly.isSelected()) {
            chbxAmountOnly.setSelected(false);
            txtMaxDiscountAmount.setText("");
            txtMaxDiscountAmount.setEnabled(false);

            txtDiscountPercentage.setEnabled(true);
        } else {
            chbxAmountOnly.setEnabled(true);
            txtMaxDiscountAmount.setEnabled(true);
        }
        validateFields();
    }//GEN-LAST:event_chbxPercentageOnlyActionPerformed

    private void chbxAmountOnlyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chbxAmountOnlyActionPerformed
        if (chbxAmountOnly.isSelected()) {
            chbxPercentageOnly.setSelected(false);
            txtDiscountPercentage.setText("");
            txtDiscountPercentage.setEnabled(false);

            txtMaxDiscountAmount.setEnabled(true);
        } else {
            chbxPercentageOnly.setEnabled(true);
            txtDiscountPercentage.setEnabled(true);
        }
        validateFields();
    }//GEN-LAST:event_chbxAmountOnlyActionPerformed

    private void dpExpDatePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_dpExpDatePropertyChange
        validateFields();
    }//GEN-LAST:event_dpExpDatePropertyChange

    private void loadVouchers() {
        DefaultTableModel tableModel = (DefaultTableModel) tblVouchers.getModel();
        tableModel.setRowCount(0);
        VoucherDao.getInstance().getAllNonExpired()
                .forEach(voucher -> {
                    tableModel.addRow(new Object[]{
                        voucher.getId(),
                        voucher.getName(),
                        voucher.getMinRank().getName(),
                        voucher.getExpDate().toString()
                    });
                });
    }

    private void validateFields() {
        try {
            double minCost = Double.parseDouble(txtMinCost.getText());
            double discountPercentage = Double.parseDouble(txtDiscountPercentage.getText().isEmpty() ? "-1" : txtDiscountPercentage.getText());
            double maxDiscountAmount = Double.parseDouble(txtMaxDiscountAmount.getText().isEmpty() ? "-1" : txtMaxDiscountAmount.getText());
            if (minCost >= 0
                    && ((discountPercentage == -1) || (discountPercentage > 0 && discountPercentage <= 100))
                    && (maxDiscountAmount == -1 || maxDiscountAmount > 0)
                    && ((!chbxPercentageOnly.isSelected() && !chbxAmountOnly.isSelected() && discountPercentage != -1 && maxDiscountAmount != -1)
                    || (chbxPercentageOnly.isSelected() && discountPercentage != -1)
                    || (chbxAmountOnly.isSelected() && maxDiscountAmount != -1))
                    && dpExpDate.getDate() != null && !Utils.toLocalDate(dpExpDate.getDate()).isBefore(LocalDate.now())) {
                btnSave.setEnabled(true);
            } else {
                btnSave.setEnabled(false);
            }
        } catch (Exception ex) {
            btnSave.setEnabled(false);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageVoucher.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageVoucher.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageVoucher.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageVoucher.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageVoucher().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<Rank> cbxRank;
    private javax.swing.JCheckBox chbxAmountOnly;
    private javax.swing.JCheckBox chbxPercentageOnly;
    private com.toedter.calendar.JDateChooser dpExpDate;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblVouchers;
    private javax.swing.JTextField txtDiscountPercentage;
    private javax.swing.JTextField txtMaxDiscountAmount;
    private javax.swing.JTextField txtMinCost;
    // End of variables declaration//GEN-END:variables
}
